name: where_my_pumpkin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  http: ^1.2.2
  logger: ^2.4.0
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.5.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/env/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeueMedium.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeueBold.ttf
          weight: 700


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
